version: '3'
services:
  bandiera:
    image: us.gcr.io/ops-support-191021/bandiera:$VERSION
    volumes:
      - .:/app
    command: 'bundle exec shotgun -p 5000 -o 0.0.0.0 -s puma'
    ports:
      - '5000:5000'
    environment:
      RACK_ENV: 'development'
      DATABASE_URL: 'mysql2://root@mysql/bandiera'
      LOG_TO_STDOUT: 'true'
      RACK_CORS_ORIGINS: '*'
    
  test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    command: 'bundle exec guard -i -p -l 1'
    environment:
      RACK_ENV: 'test'
      LOG_TO_STDOUT: 'true'

  mysql:
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=bandiera
  
volumes:
 mysql_data:

